import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import './styles.css'

const image = name => `/static/images/${name || 'default_place.svg'}`
const api = async (path, options = {}) => {
  const response = await fetch(`/api${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.message || 'Something went wrong.')
  return data
}

function Layout({ children, user, setUser }) {
  const navigate = useNavigate()
  const logout = async () => { await api('/auth/logout', { method: 'POST' }); setUser(null); navigate('/') }
  return <>
    <header className="topbar"><Link className="brand" to="/"><span className="brand-mark">SK</span><span><b>Smart Kolhapur</b><small>Travel slowly. Feel deeply.</small></span></Link>
      <nav>{[['/', 'Explore'], ['/hotels', 'Find a stay'], ['/about', 'About']].map(([to, label]) => <NavLink key={to} to={to} end={to === '/'}>{label}</NavLink>)}{user ? <><NavLink to="/favorites">Saved</NavLink><NavLink to="/bookings">Bookings</NavLink><button className="link-button" onClick={logout}>Sign out</button></> : <><NavLink to="/login">Sign in</NavLink><Link className="nav-cta" to="/signup">Join the guide</Link></>}</nav>
    </header><main>{children}</main><footer><div><b>Smart Kolhapur Guide</b><p>A considered way to discover the places, stories and stays around Kolhapur.</p></div><span>Made for curious travellers · Maharashtra</span></footer>
  </>
}

function Shell({ children, user, setUser }) { return <Layout user={user} setUser={setUser}><>{children}</></Layout> }
function Notice({ children, error }) { return <div className={error ? 'notice error' : 'notice'}>{children}</div> }
function Loading() { return <div className="loading">Loading your guide<span>•</span><span>•</span><span>•</span></div> }

function PlaceCard({ place, saved, toggle }) { return <article className="place-card"><div className="card-image"><img src={image(place.image_filename)} alt={place.name} onError={e => { e.currentTarget.src = image('default_place.svg') }} /><button className={`save ${saved ? 'saved' : ''}`} onClick={() => toggle(place.id, 'place')} aria-label="Save destination">{saved ? '♥' : '♡'}</button><span>{place.category}</span></div><div className="card-body"><p className="eyebrow">{place.tagline}</p><h3>{place.name}</h3><p>{place.short_description}</p><div className="card-actions"><Link className="text-link" to={`/place/${place.id}`}>Read the story →</Link><a className="map-link" href={`https://www.google.com/maps/search/?api=1&query=${place.latitude},${place.longitude}`} target="_blank" rel="noreferrer">Map ↗</a></div></div></article> }

function Home({ user }) {
  const [places, setPlaces] = useState([]), [query, setQuery] = useState(''), [category, setCategory] = useState('all'), [error, setError] = useState('')
  const [saved, setSaved] = useState(new Set(user?.favorites?.places || []))
  useEffect(() => { api('/places').then(setPlaces).catch(e => setError(e.message)) }, [])
  useEffect(() => { setSaved(new Set(user?.favorites?.places || [])) }, [user])
  const toggle = async (id, type) => { try { const result = await api('/favorites/toggle', { method: 'POST', body: JSON.stringify({ item_id: id, item_type: type }) }); setSaved(current => { const next = new Set(current); result.action === 'added' ? next.add(id) : next.delete(id); return next }) } catch (e) { setError(e.message) } }
  const filtered = places.filter(p => (category === 'all' || p.category === category) && (!query || `${p.name} ${p.description} ${p.category}`.toLowerCase().includes(query.toLowerCase())))
  const categories = [...new Set(places.map(p => p.category))]
  return <div><section className="hero"><div className="hero-inner"><p className="eyebrow light">A local guide to Kolhapur</p><h1>Come for the history.<br /><em>Stay for the feeling.</em></h1><p className="hero-copy">From Ambabai's evening bells to misty Sahyadri mornings, find the places that make Kolhapur worth remembering.</p><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search temples, forts, lakes, food..." /><kbd>/</kbd></div></div></section><section className="content-section"><div className="section-heading"><div><p className="eyebrow">Start with a story</p><h2>Places with a sense of place</h2></div><Link className="arrow-link" to="/hotels">Need a room? Find a stay →</Link></div><div className="filters"><button className={category === 'all' ? 'active' : ''} onClick={() => setCategory('all')}>All places</button>{categories.map(c => <button className={category === c ? 'active' : ''} key={c} onClick={() => setCategory(c)}>{c}</button>)}</div>{error && <Notice error>{error}</Notice>}{!places.length && !error ? <Loading /> : <div className="place-grid">{filtered.map(place => <PlaceCard key={place.id} place={place} saved={saved.has(place.id)} toggle={toggle} />)}</div>}{places.length > 0 && !filtered.length && <div className="empty"><h3>No places found</h3><p>Try a broader search or choose another category.</p></div>}</section></div>
}

function HotelCard({ hotel, saved, toggle, destination }) { return <article className="hotel-card"><img src={image(hotel.image_filename || 'default_hotel.svg')} alt={hotel.name} onError={e => { e.currentTarget.src = image('default_hotel.svg') }} /><div className="hotel-main"><div className="hotel-heading"><div><p className="eyebrow">{hotel.distance_km ?? '—'} km from {destination || 'your destination'}</p><h3>{hotel.name}</h3></div><button className={`save ${saved ? 'saved' : ''}`} onClick={() => toggle?.(hotel.id, 'hotel')} aria-label="Save hotel">{saved ? '♥' : '♡'}</button></div><p>{hotel.description}</p><div className="tags">{(hotel.facilities || []).slice(0, 5).map(f => <span key={f}>{f}</span>)}</div></div><div className="hotel-side"><strong>₹{hotel.price_per_night}</strong><small>per night</small><span className="hotel-distance">⌖ {hotel.distance_km ?? '—'} km away</span><b>★ {hotel.rating}</b><button className="button small" onClick={() => window.open(`/booking?hotel=${hotel.id}`, '_self')}>Book this stay</button><a href={`https://www.google.com/maps/dir/?api=1&destination=${hotel.latitude},${hotel.longitude}`} target="_blank" rel="noreferrer">Directions ↗</a></div></article> }

function Hotels({ user }) { const [params] = useSearchParams(); const [places, setPlaces] = useState([]); const [hotels, setHotels] = useState([]); const [form, setForm] = useState({ destination: params.get('destination') || '', priority: 'balanced', budget_min: 500, budget_max: 10000, rating: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saved, setSaved] = useState(new Set(user?.favorites?.hotels || []));
  useEffect(() => { Promise.all([api('/places'), api('/recommendations?priority=balanced&budget_min=500&budget_max=10000&rating=1')]).then(([p, result]) => { setPlaces(p); setHotels(result.hotels || []) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  const recommend = async e => { e.preventDefault(); setLoading(true); try { const q = new URLSearchParams(form); const result = await api(`/recommendations?${q}`); setHotels(result.hotels); } catch (e) { setError(e.message) } finally { setLoading(false) } }
  const toggle = async (id, type) => { try { const result = await api('/favorites/toggle', { method: 'POST', body: JSON.stringify({ item_id: id, item_type: type }) }); setSaved(current => { const next = new Set(current); result.action === 'added' ? next.add(id) : next.delete(id); return next }) } catch (e) { setError(e.message) } }
  const selected = places.find(p => p.id === form.destination)
  return <section className="content-section hotels-page"><div className="section-heading"><div><p className="eyebrow">A better night, after a full day</p><h1>Find your kind of stay</h1><p className="lede">Tell us what matters and we will put the most suitable nearby hotels first.</p></div></div><div className="finder"><form onSubmit={recommend}><label>Staying near<select value={form.destination} onChange={e => setForm({ ...form, destination: e.target.value })}><option value="">Kolhapur city centre</option>{places.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}><option value="balanced">A little of everything</option><option value="proximity">Closest to the place</option><option value="budget">Best value</option><option value="rating">Highest rated</option></select></label><label>Minimum rating<select value={form.rating} onChange={e => setForm({ ...form, rating: e.target.value })}><option value="1">Any rating</option><option value="3.5">3.5 and above</option><option value="4">4 and above</option><option value="4.5">4.5 and above</option></select></label><button className="button" type="submit">Show me stays</button></form></div>{error && <Notice error>{error}</Notice>}{loading ? <Loading /> : <div className="hotel-list">{hotels.map(h => <HotelCard key={h.id} hotel={h} saved={saved.has(h.id)} toggle={toggle} destination={selected?.name} />)}</div>}</section> }

function PlaceDetail() { const { id } = useParams(); const [place, setPlace] = useState(null); const [hotels, setHotels] = useState([]); useEffect(() => { Promise.all([api('/places'), api('/hotels')]).then(([p, h]) => { const found = p.find(x => x.id === id); setPlace(found); const all = h.hotels || h; setHotels(all.filter(x => x.destination_id === id).slice(0, 4)) }) }, [id]); if (!place) return <Loading />; return <section className="detail"><Link className="back" to="/">← All destinations</Link><div className="detail-hero"><img src={image(place.image_filename)} alt={place.name} /><div><p className="eyebrow">{place.category} · {place.best_time_to_visit}</p><h1>{place.name}</h1><p className="lead">{place.tagline}</p></div></div><div className="story"><div><p>{place.description}</p><h2>Why it matters</h2><p>{place.historical_background}</p></div><aside><b>Good to know</b><p>Open: {place.timings}</p><p>Entry: {place.entry_fee}</p><Link className="button" to={`/hotels?destination=${place.id}`}>Find nearby stays</Link></aside></div>{hotels.length > 0 && <><h2>Stay nearby</h2><div className="hotel-list">{hotels.map(h => <HotelCard key={h.id} hotel={h} destination={place.name} />)}</div></>}</section> }

function AccountPage({ kind }) { const [data, setData] = useState({ places: [], hotels: [], bookings: [] }); const [error, setError] = useState(''); useEffect(() => { api(kind === 'favorites' ? '/favorites' : '/bookings').then(result => setData(result)).catch(e => setError(e.message)) }, [kind]); const items = kind === 'favorites' ? [...(data.places || []), ...(data.hotels || [])] : data.bookings || []; return <section className="content-section account-page"><p className="eyebrow">Your travel shelf</p><h1>{kind === 'favorites' ? 'Places and stays you want to remember' : 'Your bookings'}</h1>{error ? <Notice error>{error}</Notice> : !items.length ? <div className="empty"><h3>Nothing here yet</h3><p>Save a place or book a stay and it will appear here.</p><Link className="button" to={kind === 'favorites' ? '/' : '/hotels'}>Start exploring</Link></div> : <div className="place-grid">{kind === 'favorites' ? data.places.map(item => <PlaceCard key={item.id} place={item} />) : items.map(item => <article className="saved-booking" key={item.id}><p className="eyebrow">{item.status}</p><h3>{item.hotel_name}</h3><p>{item.check_in} → {item.check_out}</p><b>₹{item.total_price}</b></article>)}{kind === 'favorites' && data.hotels.map(item => <HotelCard key={item.id} hotel={item} />)}</div>}</section> }

function Booking() { const [params] = useSearchParams(); const [form, setForm] = useState({ hotel_id: params.get('hotel') || '', guest_name: '', guest_email: '', guest_phone: '', check_in: '', check_out: '', guests: 2, rooms: 1, room_type: 'Deluxe Heritage Room' }); const [message, setMessage] = useState(''); const submit = async e => { e.preventDefault(); try { const result = await api('/bookings/create', { method: 'POST', body: JSON.stringify({ ...form, payment_status: 'DEMO_CONFIRMED' }) }); setMessage(`Demo booking confirmed. Your reference is ${result.booking_id}.`) } catch (e) { setMessage(e.message) } }; return <section className="auth booking-page"><div className="auth-card"><p className="eyebrow">A simple demo reservation</p><h1>Reserve your stay.</h1><p>No real payment is taken. This academic demo creates a confirmation record.</p>{message && <Notice>{message}</Notice>}<form onSubmit={submit}>{['hotel_id','guest_name','guest_email','guest_phone','check_in','check_out'].map(field => <input key={field} required={field !== 'hotel_id'} type={field.includes('date') || field.startsWith('check_') ? 'date' : field === 'guest_email' ? 'email' : 'text'} placeholder={field.replaceAll('_', ' ')} value={form[field]} onChange={e => setForm({ ...form, [field]: e.target.value })} />)}<button className="button">Confirm demo booking</button></form></div></section> }

function Auth({ signup, setUser }) { const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', confirm_password: '', phone: '' }); const [error, setError] = useState(''); const submit = async e => { e.preventDefault(); try { const user = await api(`/auth/${signup ? 'signup' : 'login'}`, { method: 'POST', body: JSON.stringify(form) }); setUser(user.user); navigate('/') } catch (e) { setError(e.message) } }; return <section className="auth"><div className="auth-card"><p className="eyebrow">Smart Kolhapur Guide</p><h1>{signup ? 'Make this place yours.' : 'Welcome back.'}</h1><p>{signup ? 'Save the places you want to return to.' : 'Pick up where your next Kolhapur day begins.'}</p>{error && <Notice error>{error}</Notice>}<form onSubmit={submit}>{signup && <input required placeholder="Your name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} />}{signup && <input placeholder="Phone number" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} />}<input required type="email" placeholder="Email address" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><input required minLength="6" type="password" placeholder="Password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} />{signup && <input required minLength="6" type="password" placeholder="Confirm password" value={form.confirm_password} onChange={e => setForm({ ...form, confirm_password: e.target.value })} />}<button className="button" type="submit">{signup ? 'Create my account' : 'Sign in'}</button></form><p className="switch">{signup ? 'Already a member?' : 'New here?'} <Link to={signup ? '/login' : '/signup'}>{signup ? 'Sign in' : 'Join the guide'}</Link></p></div></section> }

function About() { return <section className="about"><p className="eyebrow">The idea</p><h1>A guide that feels like a good local tip.</h1><p className="lede">Smart Kolhapur brings together heritage, nature, food and places to stay without making travel feel like a spreadsheet.</p><div className="about-grid"><div><h2>Made for real days out</h2><p>Choose a destination, learn what makes it special, then find a stay that makes the day easier. Recommendations balance distance, price, rating and facilities.</p></div><div><h2>Kolhapur, thoughtfully</h2><p>From sacred places and old forts to lakeside evenings and Western Ghats trails, this is a starting point for exploring with curiosity and respect.</p></div></div></section> }

function App() { const [user, setUser] = useState(null); useEffect(() => { api('/auth/me').then(r => setUser(r.user)).catch(() => {}) }, []); return <BrowserRouter><Shell user={user} setUser={setUser}><Routes><Route path="/" element={<Home user={user} />} /><Route path="/hotels" element={<Hotels user={user} />} /><Route path="/place/:id" element={<PlaceDetail />} /><Route path="/booking" element={<Booking />} /><Route path="/favorites" element={<AccountPage kind="favorites" />} /><Route path="/bookings" element={<AccountPage kind="bookings" />} /><Route path="/login" element={<Auth setUser={setUser} />} /><Route path="/signup" element={<Auth signup setUser={setUser} />} /><Route path="/about" element={<About />} /><Route path="*" element={<Home user={user} />} /></Routes></Shell></BrowserRouter> }
createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>)
